{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira-bot.fullname" . }}-secrets
  labels:
    {{- include "jira-bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.telegramBotToken }}
  {{ .Values.secrets.telegramBotTokenKey }}: {{ .Values.secrets.telegramBotToken | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jiraUsername }}
  {{ .Values.secrets.jiraUsernameKey }}: {{ .Values.secrets.jiraUsername | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jiraApiToken }}
  {{ .Values.secrets.jiraApiTokenKey }}: {{ .Values.secrets.jiraApiToken | b64enc }}
  {{- end }}
  {{- if .Values.secrets.dbUser }}
  {{ .Values.secrets.dbUserKey }}: {{ .Values.secrets.dbUser | b64enc }}
  {{- end }}
  {{- if .Values.secrets.dbPassword }}
  {{ .Values.secrets.dbPasswordKey }}: {{ .Values.secrets.dbPassword | b64enc }}
  {{- end }}
{{- end }}
