{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira-bot.fullname" . }}-secrets
  labels:
    {{- include "jira-bot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.telegramBotToken }}
  {{ .Values.secrets.telegramBotTokenKey }}: {{ .Values.secrets.telegramBotToken | b64enc }}
  {{- end }}
  {{- if .Values.secrets.chUser }}
  {{ .Values.secrets.chUserKey }}: {{ .Values.secrets.chUser | b64enc }}
  {{- end }}
  {{- if .Values.secrets.chPassword }}
  {{ .Values.secrets.chPasswordKey }}: {{ .Values.secrets.chPassword | b64enc }}
  {{- end }}
  {{- if .Values.secrets.tokenEncryptionKey }}
  {{ .Values.secrets.tokenEncryptionKeyKey }}: {{ .Values.secrets.tokenEncryptionKey | b64enc }}
  {{- end }}
{{- end }}
